services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS}
  db:
    image: mysql:8.0.36
    container_name: mysql-8.0.36
    command: --init-file /data/application/init.sql
    restart: always
    env_file:
      - ./.env
    volumes:
      - my-db:/var/lib/mysql
      - ./database/init.sql:/data/application/init.sql
  bot:
    build: .
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && python start_bot.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    ports:
      - "8080:8000"
    depends_on:
      - bot
    networks:
      - app-tier
  subscription_checker:
    build: .
    command: python subscription_checker.py
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-tier
volumes:
  my-db:
networks:
  app-tier:
    driver: bridge